# Generated by Django 2.2 on 2019-04-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlightTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('avg_dist_to_potential_collision', models.IntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Flight')),
            ],
            options={
                'ordering': ('created',),
                'managed': True,
            },
        ),
    ]
