# Generated by Django 2.2 on 2019-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190422_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asterioddata',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asterioddata',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asteriodsbundle',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hoopdata',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hoopdata',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hoopsbundle',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positiondata',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positiondata',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positiondata',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
    ]
