# Generated by Django 2.2 on 2019-04-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190422_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asterioddata',
            name='asteriod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asteriods_data', to='service.AsteriodsBundle'),
        ),
        migrations.AlterField(
            model_name='asteriodsbundle',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asteriods', to='service.Flight'),
        ),
        migrations.AlterField(
            model_name='hoopdata',
            name='hoop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoops_data', to='service.HoopsBundle'),
        ),
        migrations.AlterField(
            model_name='hoopsbundle',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoops', to='service.Flight'),
        ),
        migrations.AlterField(
            model_name='positiondata',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='service.Flight'),
        ),
        migrations.AlterField(
            model_name='speeddata',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed', to='service.Flight'),
        ),
    ]
