# Generated by Django 2.2 on 2019-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190423_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondata',
            name='x_pos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='positiondata',
            name='y_pos',
            field=models.FloatField(default=0),
        ),
    ]
